package com.meirusfandi.ecosmartphone;

public class ModelsData {
    public static String [][] data = new String[][]{
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            },
            {
                    "Samsung",
                    "Samsung S10",
                    "Harga",
                    "Display content",
                    "Body Content",
                    "Battery Content",
                    "Seller Name",
                    "Seller Image",
                    "Product Image",
                    "Stock",
                    "Main Content"
            }
    };
}
